# Generated by Django 3.2.6 on 2021-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_link', models.CharField(max_length=100, verbose_name='Ссылка на изображение компонента слайдера')),
                ('slider_comp_text', models.CharField(max_length=50, verbose_name='Текст компонента слайдера')),
            ],
            options={
                'verbose_name': 'Компонент слайдера',
                'ordering': ['id'],
            },
        ),
    ]
