# Generated by Django 3.2.6 on 2021-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_preview_link', models.CharField(max_length=300, verbose_name='Ссылка на превью обзора')),
                ('title', models.CharField(max_length=150, verbose_name='Название обзора')),
                ('review_short_text', models.TextField(verbose_name='Краткое содержание')),
                ('review_all_text', models.TextField(verbose_name='Полное содержание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор обзора')),
                ('reviews_video_link', models.CharField(blank=True, max_length=300, verbose_name='Ссылка на видео с обзором')),
                ('reviews_photos', models.JSONField(blank=True, null=True, verbose_name='Массив ссылок на фото')),
            ],
            options={
                'verbose_name': 'Обзоры',
                'ordering': ['-id'],
            },
        ),
    ]
