# Generated by Django 3.2.6 on 2021-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviews_photos',
            field=models.JSONField(blank=True, null=True, verbose_name='Массив ссылок на фото'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviews_video_link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ссылка на видео с обзором'),
        ),
    ]
