# Generated by Django 3.2.6 on 2021-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Бренд')),
                ('slug', models.SlugField(default='', max_length=30, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('in_order', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма заказа')),
            ],
            options={
                'verbose_name': 'Продукты корзины',
                'ordering': ['cart', 'id'],
            },
        ),
    ]
