# Generated by Django 3.2.6 on 2021-09-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_title'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', to_field='title', verbose_name='Категория'),
        ),
    ]
