# Generated by Django 3.2.6 on 2021-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birh_date',
            field=models.DateField(blank=True, default=None, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Фамилия'),
        ),
    ]
