# Generated by Django 3.2.6 on 2021-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210830_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birh_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
